[package]
name = "conways_bacteria"
version = "0.1.0"
authors = ["jpond"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rayon = "1.3.1"
gif = "0.10.3"
calcify = "0.8.1"
